define({
    "email" : {
        "ResetSubject" : "Passwort Zurücksetzug",
        "Reset" : "Bitte klicken Sie auf den Link um Ihr Passwort zuerückzusetzen: {0}",
        "RegisterSubject" : "Email Bestätigung",
        "Register" : "Bitte klicket Sie auf den Link um Ihre Email zu bestätigen: {0}",
        "GatewayAlertSubject" : "Gateway getrennt",
        "GatewayAlert" : "Ihr 37coins Gateway ist seid ein paar Minuten nicht erreichbar. Bitte ueberprüfen Sie das Gerät. Nach langer Ausfallzeit werden wir Kunden informieren.",
        "Byebye" : "Mit freundlichen Grüßen,\n\n{0}"
    },
    "commands" : {
        "SignupCmd" : ["signupDE"],
        "HelpCmd" : ["hilfe","hilf"],
        "DepositReqCmd" : ["depot","adresse","adr","einzahlen"],
        "BalanceCmd" : ["bilanz","bil","saldo","guthaben","haben","kontostand"],
        "TransactionsCmd" : ["transaktionen","umsätze","umsatz"],
        "WithdrawalReqCmd" : ["sende","schick","schicken"],
        "VoiceCmd" : ["anruf","pin"],
        "ChargeCmd" : ["fordern","forder"],
        "ProductCmd" : ["produkt"],
        "PayCmd" : ["zahlen"],
        "PriceCmd" : ["preis"],
        "SellCmd" : ["verkaufen","verkaufe","verkauf"],
        "BuyCmd" : ["kaufen","kaufe","kauf"]
    },
    "sms" : {
        "Signup" : "Wilkommen zur 37 Koins BETA! Bitcoin via SMS. Speichere diese Nummer, sende Kommandos ans gateway. Antworte HILFE für mehr Info {0}",
        "DepositReq" : "{0}",
        "Charge" : "Zahlbar durch \"pay {0}\"",
        "Product" : "Zahlbar durch \"pay {0}\"",
        "DepositNotify" : "{0}{2}{1} zu Ihnen angewiesen. Verfügbar in etwa 10 min. Sie werden benachrichtigt.",
        "DepositConf" : "Sie haben {0}{2}{1} erhalten.",
        "DepositConfSndr" : "Sie haben {0}{3}{1} von {2} erhalten.",
        "DepositConfSndrMsg" : "Sie haben {0}{4}{1} von {2} fuer \"{3}\" erhalten.",
        "Balance" : "verfügbares Guthaben: {0}{3}{1} {2}",
        "BalanceInst" : "\r\nAntworte ADDR, für Bitcoinadresse",
        "WithdrawalReq" : "Wollen Sie {0}{3}{1} an {2} überweisen?",
        "WithdrawalReqHelp" : "Verwenden Sie SENDE <betrag> <tel#>\r\nz.B.: SENDE 1.42EUR 5558675309\r\n<betrag>use XXUSD for US value, or just XX to indicate mili-bitcoin",
        "WithdrawalReqPay" : "Wollen Sie {0}{4}{1} an {2} für {3} zahlen?",
        "WithdrawalReqIstr" : "Um zu bestätigen, senden sie: {0}",
        "WithdrawalConf" : "{0}{3}{1} an {2} überwiesen.",
        "Help" : "Sendelimit ohne PIN: 10EUR\r\nADDR - Bitcoin Einzahlungsadresse\r\nBAL - siehe verfügbares Saldo\r\nPIN - konfiguriere PIN\r\n{0}",
        "Buy" : "Sie wurden als Käufer registriert.",
        "FormatError" : "Wir konnten Ihre Anfrage nicht verstehen. Bitte versuchen Sie es erneut.",
        "InsufficientFunds" : "Unzureichendes Guthaben.\r\nHaben: {0}{4}{1},\r\nbenötigt: {2}{4}{3}.",
        "UnknownCommand" : "Unbekannter Befehl. Antworte mit HILFE oder siehe {0}",
        "Timeout" : "Die Transaktion wurde nicht rechtzeitig bestätigt.",
        "TransactionFailed" : "Transaktion aus unbekanntem Grund fehlgeschlagen.",
        "TransactionCanceled" : "Transaktion abgebrochen.",
        "Unavailable" : "Der Service ist gerade nicht verfügbar, bitte versuchen Sie es in 1 Stunde.\r\nWir bitten um Verständnis.",
        "DestinationUnreachable" : "Kein Gateway verfügbar in Zielland.",
        "BelowFee" : "Transaktionswert niedriger als Gebuehr. Übrepruefe Betrag.",
        "AccountBlocked" : "Account geblockt",
        "Overuse" : "Ihre Anfrage wurde als redundant befunden und wurde nicht ausgefuehrt.",
        "Voice" : "Anruf-PIN erfolgreich aktiviert."
    },
    "voice" : {
        "VoiceHello" : "37 Koins, Ihre internationale Geldbörse.",
        "VoiceSetup" : "Konfigurieren Sie eine Pin um Transaktionen zu sichern.",
        "VoiceCreate" : "Bitte geben Sie eine vierstellige Pin ein, gefolgt von der Raute taste.",
        "VoiceConfirm" : "Bitte wiederholen Sie ihre Pin, gefolgt von der Raute taste.",
        "VoiceMerchantConfirm" : "Bitte geben Sie die vierstellige Pin ein, gefolgt von der Raute taste.",
        "VoiceMismatch" : "Pins stimmen nicht überein.",
        "VoiceSuccess" : "Bitte merken Sie sich die Pin fuer die Zukunft.",
        "VoiceEnter" : "Bitte geben Sie ihre vierstellige Pin ein, gefolgt von der Raute taste.",
        "VoiceOk" : "Korrekt. Transaktion wird ausgeführt.",
        "VoiceFail" : "Pin ungültig, nach 3 Versuchen wird Ihr Konto gesperrt.",
        "VoiceRegister" : "Grüße von 37 Koins. Ihr Verifizierungscode lautet ${payload}. Bitte geben Sie ${payload} ein um zu verifizieren."
    }
});
