define({
    "email" : {
        "ResetSubject" : "Restablecer la contraseña",
        "Reset" : "Por favor, haga clic en este enlace para restablecer su contraseña: {0}",
        "RegisterSubject" : "Mensaje de verificación",
        "Register" : "Por favor haga clic en este enlace para verificar su cuenta: {0}",
        "GatewayAlertSubject" : "Portal sin conexión",
        "GatewayAlert" : "Su {0} portal se encuentra fuera de línea desde hace unos minutos. Por favor, reanude su operación. Notificaremos a los clientes después de un paro prolongado.",
        "Byebye" : "Saludos cordiales, adiós\r\n{0}"
    },
    "commands" : {
        "SignupCmd" : ["signupES"],
        "HelpCmd" : ["ayuda","ayd","ayu","asistencia","asist"],
        "DepositReqCmd" : ["dir","dirección","direccion","depósito","deposito","cuenta"],
        "BalanceCmd" : ["balanza","sal","saldo"],
        "TransactionsCmd" : ["transacciones","tran","trans","tx","transaccion","transacción"],
        "WithdrawalReqCmd" : ["enviando","enviar","enviado","envia","envía"],
        "VoiceCmd" : ["voz","pin"],
        "ChargeCmd" : ["cobrar","cobro","cobra"],
        "ProductCmd" : ["prod","producto"],
        "PayCmd" : ["pagar","pago"],
        "PriceCmd" : ["precio"],
        "SellCmd" : ["vender","vendo","vende"],
        "BuyCmd" : ["comprar","compro","compra"]
    },
    "sms" : {
        "Signup" : "¡Bienvenido! Su monedero mundial. Guarde este número, envíe comandos a este portal. Responda AYUDA para más información. {0}",
        "DepositReq" : "{0}",
        "Charge" : "Se puede pagar a traves \"PAGAR {0}\"",
        "Product" : "Se puede pagar a traves \"PAGAR {0}\"",
        "DepositNotify" : "{0}{2}{1}  en camino a su monedero. Disponibles en aproximadamente 10 minutos, se notificará cuando se haya completado.",
        "DepositConf" : "Usted ha recibido {0}{2}{1} en su monedero.",
        "DepositConfSndr" : "Usted ha recibido {0}{3}{1} de {2}",
        "DepositConfSndrMsg" : "Usted ha recibido {0}{4}{1} de {2} por: \"{3}\"",
        "Balance" : "Tiene disponible {0}{3}{1} {2}",
        "BalanceInst" : "\r\nResponda DIR, para obtener su dirección bitcoin.",
        "WithdrawalReq" : "¿Quieres enviar {0}{3}{1} de su cuenta a {2}?",
        "WithdrawalReqHelp" : "Por favor utilice ENIVAR<cantidad><número celular> Ej: ENVIAR 3000COP 3156963464 <cantidad>utilice XXCOP para valor en CO, o simplemente XX para indicar mili-bitcoin", 
        "WithdrawalReqPay" : "¿Pagar {0}{4}{1} a {2} por: {3}?",
        "WithdrawalReqIstr" : "Para confirmar la transacción, responda con: {0}",
        "WithdrawalConf" : "Hemos transferido {0}{3}{1} a {2}.",
        "Help" : "DIR - Obtén dirección para depósitos\r\nBAL - Obtén balance en mBTC\r\nPIN - Establece PIN secreto\r\n{0}",
        "Buy" : "Su número se ha añadido como un comprador.",
        "FormatError" : "Tuvimos problemas entendiendo su solicitud. Por favor, vuelva a enviarlo en el formato correcto.",
        "InsufficientFunds" : "Usted tiene fondos insuficientes: su balance es: {0}{4}{1}, y {2}{4}{3} es requerido para completar la transacción.",
        "UnknownCommand" : "Has enviado un comando desconocido. Responde AYUDA o ingresa a {0}",
        "Timeout" : "Ninguna confirmación fue recibida dentro del tiempo dado, la transacción ha sido cancelada.",
        "TransactionFailed" : "Transacción falló debido a razones desconocidas.",
        "TransactionCanceled" : "La transacción ha sido cancelada.",
        "Unavailable" : "{0} no está disponible en este momento, por favor intente de nuevo en 1 hora.\r\nDisculpe la molestia ocasionada.",
        "DestinationUnreachable" : "Ningún portal fue encontrado en el país al que usted está intentando enviar bitcoins. Sugiérale a su amigo abrir un portal en {0}",
        "BelowFee" : "Esta transacción no vale la pena ser enviada. Vuelva a verificar la cantidad.",
        "AccountBlocked" : "La cuenta está bloqueada",
        "Overuse" : "Su comando fue encontrado redundante y saltó para evitar un alto costo.",
        "Voice" : "PIN de seguridad activado exitosamente"
    },
    "voice" : {
        "VoiceHello" : "37 Coins, su monedero mundial.",
        "VoiceSetup" : "Para asegurar transacciones significantes, por favor cree un PIN de 4 dígitos.",
        "VoiceCreate" : "Por favor, ingrese un nuevo PIN de 4 dígitos, seguido de la tecla numeral.",
        "VoiceConfirm" : "Por favor, repita su nuevo PIN de 4 dígitos, seguido de la tecla numeral.",
        "VoiceMerchantConfirm" : "Por favor, ingrese el número de 4 dígitos, seguido de la tecla numeral.",
        "VoiceMismatch" : "PIN no coincide. Por favor, inténtalo de nuevo.",
        "VoiceSuccess" : "Por favor Recuerde su PIN para transacciones en el futuro.",
        "VoiceEnter" : "Por favor ingrese su PIN de 4 dígitos, seguido de la tecla numeral.",
        "VoiceOk" : "Correcto. La transacción se está ejecutando.",
        "VoiceFail" : "El pasador que has puesto no es correcto, su cuenta será bloqueada después de 3 intentos fallidos.",
        "VoiceRegister" : "Hola desde 37 Coins. Su código de verificación es $ {payload}. Por favor, ingrese $ {payload} para completar la verificación."
    }
});
